# Generated by Django 4.2.30 on 2026-05-12 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingressos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingresso',
            name='cpf',
            field=models.CharField(default=0, max_length=14),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ingresso',
            name='telefone',
            field=models.CharField(max_length=30),
        ),
    ]
