# Generated by Django 5.2.14 on 2026-05-14 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingressos', '0003_pedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='eventos/'),
        ),
    ]
