# Generated by Django 5.2.14 on 2026-05-15 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingressos', '0004_evento_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingresso',
            name='data_checkin',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
