# Generated by Django 4.2.30 on 2026-05-27 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingressos', '0005_ingresso_data_checkin'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingresso',
            name='cancelado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ingresso',
            name='data_cancelamento',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
