# Generated by Django 4.2.30 on 2026-06-04 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingressos', '0006_ingresso_cancelado_ingresso_data_cancelamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValidacaoAssociado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=14)),
                ('nome', models.CharField(max_length=200)),
                ('crm', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(blank=True, max_length=30)),
                ('codigo', models.CharField(max_length=6)),
                ('confirmado', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
