# Generated by Django 4.2.30 on 2026-06-05 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingressos', '0007_validacaoassociado'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='valor_associado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='evento',
            name='valor_nao_associado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
