# Generated by Django 4.2.30 on 2026-06-06 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingressos', '0008_evento_valor_associado_evento_valor_nao_associado'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingresso',
            name='associado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pedido',
            name='associado',
            field=models.BooleanField(default=False),
        ),
    ]
