# Generated by Django 4.2.30 on 2026-06-09 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingressos', '0009_ingresso_associado_pedido_associado'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='quantidade_associado',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='evento',
            name='quantidade_nao_associado',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
