# Generated by Django 4.2.30 on 2026-06-09 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingressos', '0010_evento_quantidade_associado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='forma_pagamento',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
