# Generated by Django 4.2.30 on 2026-06-09 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingressos', '0011_pedido_forma_pagamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingresso',
            name='forma_pagamento',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
