# Generated by Django 4.2.30 on 2026-06-14 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingressos', '0012_ingresso_forma_pagamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Evento aberto para vendas'),
        ),
    ]
