# Generated by Django 4.2.30 on 2026-07-10 01:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ingressos', '0013_evento_ativo'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='beneficio_primeira_compra',
            field=models.BooleanField(default=False, verbose_name='Gerar 2 ingressos na primeira compra'),
        ),
        migrations.AddField(
            model_name='evento',
            name='exclusivo_associado',
            field=models.BooleanField(default=False, verbose_name='Evento exclusivo para associados'),
        ),
        migrations.AddField(
            model_name='evento',
            name='quantidade_compras_seguintes',
            field=models.PositiveIntegerField(default=1, verbose_name='Ingressos nas compras seguintes'),
        ),
        migrations.AddField(
            model_name='evento',
            name='quantidade_primeira_compra',
            field=models.PositiveIntegerField(default=2, verbose_name='Ingressos na primeira compra'),
        ),
        migrations.AddField(
            model_name='ingresso',
            name='pedido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingressos', to='ingressos.pedido'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='asaas_payment_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
