# Generated by Django 4.2.30 on 2026-07-20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingressos', '0014_evento_beneficio_primeira_compra_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pedido',
            options={
                'permissions': [
                    (
                        'confirmar_pagamento_cesta_basica',
                        'Pode confirmar pagamento com cesta básica',
                    ),
                ],
            },
        ),
    ]
