# Generated by Django 4.2.30 on 2026-07-21 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingressos', '0015_pedido_confirmar_pagamento_cesta_basica_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='aceita_cartao_credito',
            field=models.BooleanField(default=True, verbose_name='Aceitar cartão de crédito'),
        ),
    ]
